In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.Variable(123)
tf.print(x)

y = tf.Variable(x + 100)
tf.print(y)

123
223


In [3]:
x = tf.Variable(123, dtype=tf.float32)
tf.print(x)

123


텐서란 배열의 집합

랭크란 배열의 차원

랭크가 0 일때(0차) 스칼라

랭크가 1 일때(1차) 백터

랭크가 2 일때(2차) 매트릭스

랭크가 3 일때(3차) 텐서

In [4]:
a = 100
ts1 = np.array(a)
print(ts1.shape)
ts1

()


array(100)

In [5]:
b = [1,2,3]
ts2 = np.array(b)
print(ts2.shape)
ts2

(3,)


array([1, 2, 3])

In [6]:
c = [[10,20,30], [100,200,300]]
ts3 = np.array(c)
print(ts3.shape)
ts3

(2, 3)


array([[ 10,  20,  30],
       [100, 200, 300]])

In [7]:
node1 = tf.constant(3.0, dtype=tf.float32, name='hello')
print(node1)
tf.print(node1)

tf.Tensor(3.0, shape=(), dtype=float32)
3


In [8]:
node2 = tf.constant(4.0, name='wolrd')
print(node2)
tf.print(node2)

tf.Tensor(4.0, shape=(), dtype=float32)
4


In [9]:
node3 = tf.add(node1, node2)
print(node3)
tf.print(node3)

tf.Tensor(7.0, shape=(), dtype=float32)
7


In [10]:
import pandas as pd
import numpy as np

## 데이터 생성
data = {
    'gender' : ['male','femail','male','male','femail','male','male','femail'],
    'car' : ['N','Y','Y','Y','N','N','N','Y'],
    'family_size' : [1,2,3,5,2,3,2,1],
    'work_phone' : [0,0,0,0,1,0,0,0],
    'income' : [180,190,200,300,220,190,350,250]
}
df = pd.DataFrame(data)

In [11]:
pd.get_dummies(df, drop_first=True, dtype='int')

family_size  work_phone  income  gender_male  car_Y
0            1           0     180            1      0
1            2           0     190            0      1
2            3           0     200            1      1
3            5           0     300            1      1
4            2           1     220            0      0
5            3           0     190            1      0
6            2           0     350            1      0
7            1           0     250            0      1

In [12]:
pd.get_dummies(df, columns = ['gender', 'car', 'work_phone'], dtype='int')

family_size  income  gender_femail  gender_male  car_N  car_Y  \
0            1     180              0            1      1      0   
1            2     190              1            0      0      1   
2            3     200              0            1      0      1   
3            5     300              0            1      0      1   
4            2     220              1            0      1      0   
5            3     190              0            1      1      0   
6            2     350              0            1      1      0   
7            1     250              1            0      0      1   

   work_phone_0  work_phone_1  
0             1             0  
1             1             0  
2             1             0  
3             1             0  
4             0             1  
5             1             0  
6             1             0  
7             1             0

In [13]:
pd.get_dummies(df, columns=['gender', 'car', 'work_phone'], drop_first=True, dtype='int')

family_size  income  gender_male  car_Y  work_phone_1
0            1     180            1      0             0
1            2     190            0      1             0
2            3     200            1      1             0
3            5     300            1      1             0
4            2     220            0      0             1
5            3     190            1      0             0
6            2     350            1      0             0
7            1     250            0      1             0

In [14]:
label = df['car']
label.unique()

array(['N', 'Y'], dtype=object)

In [15]:
label.values
label.values.reshape(-1,1)

array([['N'],
       ['Y'],
       ['Y'],
       ['Y'],
       ['N'],
       ['N'],
       ['N'],
       ['Y']], dtype=object)

In [16]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
ohe = OneHotEncoder(sparse=False) # 행렬반환
ohe.fit(label.values.reshape(-1,1))

c:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(sparse=False, sparse_output=False)

In [17]:
print(ohe.transform(label.values.reshape(-1,1)))

[[1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]


In [18]:
label_test = np.array([['N'],['N']])
print(ohe.transform(label_test))

[[1. 0.]
 [1. 0.]]


In [19]:
ohe.categories_

[array(['N', 'Y'], dtype=object)]

In [20]:
label_ohe = ohe.transform(label.values.reshape(-1,1))
ohe_df = pd.DataFrame(label_ohe, columns=['car_N', 'car_Y'])
ohe_df

car_N  car_Y
0    1.0    0.0
1    0.0    1.0
2    0.0    1.0
3    0.0    1.0
4    1.0    0.0
5    1.0    0.0
6    1.0    0.0
7    0.0    1.0

In [39]:
fish_target = np.concatenate((np.ones(35), np.zeros(14)))
fish_target

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
x = np.column_stack((df, ohe_df))

In [32]:
x = pd.DataFrame(x)

In [33]:
print(display(x), display(df), display(ohe_df))

0  1  2  3    4    5    6
0    male  N  1  0  180  1.0  0.0
1  femail  Y  2  0  190  0.0  1.0
2    male  Y  3  0  200  0.0  1.0
3    male  Y  5  0  300  0.0  1.0
4  femail  N  2  1  220  1.0  0.0
5    male  N  3  0  190  1.0  0.0
6    male  N  2  0  350  1.0  0.0
7  femail  Y  1  0  250  0.0  1.0

gender car  family_size  work_phone  income
0    male   N            1           0     180
1  femail   Y            2           0     190
2    male   Y            3           0     200
3    male   Y            5           0     300
4  femail   N            2           1     220
5    male   N            3           0     190
6    male   N            2           0     350
7  femail   Y            1           0     250

car_N  car_Y
0    1.0    0.0
1    0.0    1.0
2    0.0    1.0
3    0.0    1.0
4    1.0    0.0
5    1.0    0.0
6    1.0    0.0
7    0.0    1.0

None None None


In [35]:
x.columns = ['1', '2', '3', '4', '5', '6', '7']

In [36]:
x.columns

Index(['1', '2', '3', '4', '5', '6', '7'], dtype='object')

In [38]:
fish_target = np.concatenate((np.ones(35), np.zeros(14)))
fish_target

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])