In [2]:
from pandas import read_csv
import pandas as pd

In [3]:
df = pd.read_csv('https://bit.ly/ds-house-price')
df

지역명               규모구분    연도   월 분양가격(㎡)
0     서울                 전체  2015  10    5841
1     서울         전용면적 60㎡이하  2015  10    5652
2     서울   전용면적 60㎡초과 85㎡이하  2015  10    5882
3     서울  전용면적 85㎡초과 102㎡이하  2015  10    5721
4     서울        전용면적 102㎡초과  2015  10    5879
...   ..                ...   ...  ..     ...
4500  제주                 전체  2020   2    3955
4501  제주         전용면적 60㎡이하  2020   2    4039
4502  제주   전용면적 60㎡초과 85㎡이하  2020   2    3962
4503  제주  전용면적 85㎡초과 102㎡이하  2020   2     NaN
4504  제주        전용면적 102㎡초과  2020   2    3601

[4505 rows x 5 columns]

In [4]:
df = df.rename(columns={'분양가격(㎡)':'분양가격'})
df

지역명               규모구분    연도   월  분양가격
0     서울                 전체  2015  10  5841
1     서울         전용면적 60㎡이하  2015  10  5652
2     서울   전용면적 60㎡초과 85㎡이하  2015  10  5882
3     서울  전용면적 85㎡초과 102㎡이하  2015  10  5721
4     서울        전용면적 102㎡초과  2015  10  5879
...   ..                ...   ...  ..   ...
4500  제주                 전체  2020   2  3955
4501  제주         전용면적 60㎡이하  2020   2  4039
4502  제주   전용면적 60㎡초과 85㎡이하  2020   2  3962
4503  제주  전용면적 85㎡초과 102㎡이하  2020   2   NaN
4504  제주        전용면적 102㎡초과  2020   2  3601

[4505 rows x 5 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4505 entries, 0 to 4504
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   지역명     4505 non-null   object
 1   규모구분    4505 non-null   object
 2   연도      4505 non-null   int64 
 3   월       4505 non-null   int64 
 4   분양가격    4210 non-null   object
dtypes: int64(2), object(3)
memory usage: 176.1+ KB


In [6]:
df['분양가격'].astype(int)

ValueError: invalid literal for int() with base 10: '  '

In [7]:
df.loc[df['분양가격'] == '  ', '분양가격'] = '0'

In [8]:
df['분양가격'].astype(int)

ValueError: cannot convert float NaN to integer

In [9]:
df['분양가격'] = df['분양가격'].fillna('0')

In [10]:
df['분양가격'].astype(int)

ValueError: invalid literal for int() with base 10: '6,657'

In [11]:
df.loc[df['분양가격'] == '6,657']

지역명 규모구분    연도   월   분양가격
2125  서울   전체  2017  11  6,657

In [17]:
df['분양가격'] = df['분양가격'].str.replace(',', '')

In [18]:
df.loc[df['분양가격'] == '6657']

지역명 규모구분    연도   월  분양가격
2125  서울   전체  2017  11  6657

In [19]:
df['분양가격'].astype(int)

ValueError: invalid literal for int() with base 10: ''

In [20]:
df['분양가격'] = df['분양가격'].str.replace("-", '')

In [21]:
df['분양가격'].astype(int)

ValueError: invalid literal for int() with base 10: ''

In [23]:
from sklearn.preprocessing import LabelEncoder
items = ['TV', '냉장고', '전자레인지', ' 컴퓨터', '선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("인코딩 변환값:", labels)

인코딩 변환값: [1 2 5 0 4 4 3 3]


In [24]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: [' 컴퓨터' 'TV' '냉장고' '믹서' '선풍기' '전자레인지']


In [25]:
print('디코딩 원본 값:', encoder.inverse_transform([1, 2, 5, 0, 4, 4, 3, 3]))

디코딩 원본 값: ['TV' '냉장고' '전자레인지' ' 컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [26]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [30]:
# 2차원 데이터로 변환
labels = labels.reshape(-1,1)
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [31]:
# 마지막으로 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print(oh_labels.shape)
oh_labels.toarray()

(8, 6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [32]:
import pandas as pd
df = pd.DataFrame({'items':['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기','선풍기','믹서','믹서']})
df

items
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [33]:
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터
0      True      False     False      False       False      False
1     False       True     False      False       False      False
2     False      False     False      False        True      False
3     False      False     False      False       False       True
4     False      False     False       True       False      False
5     False      False     False       True       False      False
6     False      False      True      False       False      False
7     False      False      True      False       False      False

In [34]:
from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

In [35]:
print(iris_df.mean())
print('\nfeature 들의 분산값')
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [37]:
# MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [38]:
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print("feature들의 최소 값")
print(iris_df_scaled.min())
print("\nfeature들의 최대값")
print(iris_df_scaled.max())

feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [39]:
from pandas import read_excel
df = read_excel("https://data.hossam.kr/C02/pre_sample.xlsx", index_col='이름')
# df

In [40]:
df1 = df.copy()
df1['직접합계'] = df['국어'] + df['영어'] + df['수학'] + df['과학']
df1

학년  성별  국어   영어  수학  과학  직접합계
이름                               
철수   1  남자  98   77  88  64   327
영희   2  여자  88  120  62  72   342
민철   1  남자  92   70  83  79   324
수현   3  여자  63   60  31  71   225
호영   4  남자  75   50  90  88   303
영호   4  남자  80   88  91  72   331
용식   2  남자  82   88  79  90   339
나영   1  여자  90   92  81  95   358
석영   1  남자  91   90  89  80   350

In [41]:
df3 = df.copy()
df.iloc[0]

학년     1
성별    남자
국어    98
영어    77
수학    88
과학    64
Name: 철수, dtype: object

In [42]:
df.iloc[1:4]

학년  성별  국어   영어  수학  과학
이름                         
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71

In [43]:
df.iloc[1,2]

88

In [44]:
df.iloc[:,3]

이름
철수     77
영희    120
민철     70
수현     60
호영     50
영호     88
용식     88
나영     92
석영     90
Name: 영어, dtype: int64

In [45]:
df.iloc[:,2:].sum(axis=1)

이름
철수    327
영희    342
민철    324
수현    225
호영    303
영호    331
용식    339
나영    358
석영    350
dtype: int64

In [46]:
df3 = df.copy()
df3['합계'] = df.iloc[:, 2:].sum(axis=1)
df3

학년  성별  국어   영어  수학  과학   합계
이름                              
철수   1  남자  98   77  88  64  327
영희   2  여자  88  120  62  72  342
민철   1  남자  92   70  83  79  324
수현   3  여자  63   60  31  71  225
호영   4  남자  75   50  90  88  303
영호   4  남자  80   88  91  72  331
용식   2  남자  82   88  79  90  339
나영   1  여자  90   92  81  95  358
석영   1  남자  91   90  89  80  350

In [47]:
df.loc['철수']
df.loc[:, "국어":]

국어   영어  수학  과학
이름                 
철수  98   77  88  64
영희  88  120  62  72
민철  92   70  83  79
수현  63   60  31  71
호영  75   50  90  88
영호  80   88  91  72
용식  82   88  79  90
나영  90   92  81  95
석영  91   90  89  80

In [50]:
df.loc[:, '국어':].mean(axis=1)
df.loc[:, "국어":].var(axis=1)

이름
철수    213.583333
영희    643.666667
민철     83.333333
수현    304.916667
호영    338.916667
영호     72.916667
용식     26.250000
나영     36.333333
석영     25.666667
dtype: float64

In [51]:
df = read_excel("https://data.hossam.kr/C02/pre_sample.xlsx", index_col='이름')
df

학년  성별  국어   영어  수학  과학
이름                         
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

In [52]:
col  = ['col1','col2','col3']
row  = ['row1','row2','row3','row4','row5']
data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]

df = pd.DataFrame(data, row, col)
print(df)

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9
row4    10    11    12
row5    13    14    15


In [54]:
print(df.sample(2))

      col1  col2  col3
row2     4     5     6
row1     1     2     3


In [55]:
print(df.sample(10, replace=True)) # replace True 중복허용

      col1  col2  col3
row4    10    11    12
row2     4     5     6
row1     1     2     3
row4    10    11    12
row2     4     5     6
row3     7     8     9
row5    13    14    15
row1     1     2     3
row1     1     2     3
row5    13    14    15


In [57]:
print(df.sample(frac=0.4)) # 전체에서 40프로만 추출

      col1  col2  col3
row5    13    14    15
row2     4     5     6


In [58]:
print(df.sample(5, random_state=7))

      col1  col2  col3
row1     1     2     3
row4    10    11    12
row3     7     8     9
row2     4     5     6
row5    13    14    15


In [59]:
df = pd.DataFrame({'캠페인시작날짜':['2020.07.08','2020.07.09','2020.07.10']})
df

캠페인시작날짜
0  2020.07.08
1  2020.07.09
2  2020.07.10

In [60]:
df['캠페인시작날짜'] = df['캠페인시작날짜'].apply(lambda x : x.replace(".","-"))
df

캠페인시작날짜
0  2020-07-08
1  2020-07-09
2  2020-07-10

In [61]:
df = pd.DataFrame({'캠페인명':['aaa캠페인','bbb캠페인','ccc캠페인'],'캠페인날짜':['2020-02-01','2021-03-08','2021-11-04']})
df

캠페인명       캠페인날짜
0  aaa캠페인  2020-02-01
1  bbb캠페인  2021-03-08
2  ccc캠페인  2021-11-04

In [62]:
df.loc[(df.캠페인명=='ccc캠페인'), '캠페인날짜'] = '2021-05-30'
df

캠페인명       캠페인날짜
0  aaa캠페인  2020-02-01
1  bbb캠페인  2021-03-08
2  ccc캠페인  2021-05-30

In [64]:
ages=[0,2,10,21,23,37,31,61,20,41,32,100]
# 카테고리를 나누는 기준 설정 
bins=[1,15,25,35,60,99]
# 카테고리 설정
labels =['미성년자', '청년', '중년', '장년', '노년']

cats=pd.cut(ages,bins, labels=labels)
cats

[NaN, '미성년자', '미성년자', '청년', '청년', ..., '노년', '청년', '장년', '중년', NaN]
Length: 12
Categories (5, object): ['미성년자' < '청년' < '중년' < '장년' < '노년']

In [65]:
import os

In [66]:
df = pd.read_csv('friend.csv')
df.head()

name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager

In [67]:
df.iloc[2]

name       Nate
age          30
job     teacher
Name: 2, dtype: object

In [68]:
df['job']

0      student
1    developer
2      teacher
3      dentist
4      manager
5       intern
Name: job, dtype: object

In [69]:
df.loc[:, 'job']

0      student
1    developer
2      teacher
3      dentist
4      manager
5       intern
Name: job, dtype: object

In [70]:
df.iloc[[2,3]]

name  age      job
2   Nate   30  teacher
3  Julia   40  dentist

In [71]:
df.iloc[2:4]

name  age      job
2   Nate   30  teacher
3  Julia   40  dentist

In [72]:
df[df['age']>30]

name  age      job
3  Julia   40  dentist
4  Brian   45  manager

In [74]:
df[df['job']=='intern']

name  age     job
5  Chris   25  intern

In [75]:
# 30대이상 40대 이하
df[(df['age']>=30) & (df['age']<=40)]

name  age        job
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist

In [77]:
# 30대 미만 혹은 40대 초과
df[(df['age'] < 30) | (df['age'] > 40)]

name  age      job
0   John   20  student
4  Brian   45  manager
5  Chris   25   intern

In [78]:
# 학생과 매니저가 포함된 것을 찾고싶다
df[df['job'].apply(lambda x : x in ['student', 'manager'])]

name  age      job
0   John   20  student
4  Brian   45  manager

In [79]:
import numpy as np
df = pd.DataFrame(np.arange(12).reshape(3,4),
                  columns=['A','B','C','D'])
df.drop(['B','C'], axis=1)

A   D
0  0   3
1  4   7
2  8  11