In [1]:
from pandas import read_csv
import pandas as pd

In [26]:
df = pd.read_csv('https://bit.ly/ds-house-price')
df

지역명               규모구분    연도   월 분양가격(㎡)
0     서울                 전체  2015  10    5841
1     서울         전용면적 60㎡이하  2015  10    5652
2     서울   전용면적 60㎡초과 85㎡이하  2015  10    5882
3     서울  전용면적 85㎡초과 102㎡이하  2015  10    5721
4     서울        전용면적 102㎡초과  2015  10    5879
...   ..                ...   ...  ..     ...
4500  제주                 전체  2020   2    3955
4501  제주         전용면적 60㎡이하  2020   2    4039
4502  제주   전용면적 60㎡초과 85㎡이하  2020   2    3962
4503  제주  전용면적 85㎡초과 102㎡이하  2020   2     NaN
4504  제주        전용면적 102㎡초과  2020   2    3601

[4505 rows x 5 columns]

In [27]:
df = df.rename(columns={'분양가격(㎡)':'분양가격'})
df

지역명               규모구분    연도   월  분양가격
0     서울                 전체  2015  10  5841
1     서울         전용면적 60㎡이하  2015  10  5652
2     서울   전용면적 60㎡초과 85㎡이하  2015  10  5882
3     서울  전용면적 85㎡초과 102㎡이하  2015  10  5721
4     서울        전용면적 102㎡초과  2015  10  5879
...   ..                ...   ...  ..   ...
4500  제주                 전체  2020   2  3955
4501  제주         전용면적 60㎡이하  2020   2  4039
4502  제주   전용면적 60㎡초과 85㎡이하  2020   2  3962
4503  제주  전용면적 85㎡초과 102㎡이하  2020   2   NaN
4504  제주        전용면적 102㎡초과  2020   2  3601

[4505 rows x 5 columns]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4505 entries, 0 to 4504
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   지역명     4505 non-null   object
 1   규모구분    4505 non-null   object
 2   연도      4505 non-null   int64 
 3   월       4505 non-null   int64 
 4   분양가격    4210 non-null   object
dtypes: int64(2), object(3)
memory usage: 176.1+ KB


In [29]:
df['분양가격'].astype(int)

ValueError: invalid literal for int() with base 10: '  '

In [30]:
df.loc[df['분양가격'] == '  ', '분양가격'] = '0'

In [31]:
df['분양가격'].astype(int)

ValueError: cannot convert float NaN to integer

In [32]:
df['분양가격'] = df['분양가격'].fillna('0')

In [33]:
df.loc[df['분양가격'] == '6,657']

지역명 규모구분    연도   월   분양가격
2125  서울   전체  2017  11  6,657

In [34]:
df['분양가격'] = df['분양가격'].str.replace(',', '')

In [35]:
df.loc[df['분양가격'] == '6657']

지역명 규모구분    연도   월  분양가격
2125  서울   전체  2017  11  6657

In [36]:
df['분양가격'].astype(int)

ValueError: invalid literal for int() with base 10: '-'

In [37]:
df['분양가격'] = df['분양가격'].str.replace('-', '0')

In [38]:
df['분양가격'].astype(int)

0       5841
1       5652
2       5882
3       5721
4       5879
        ... 
4500    3955
4501    4039
4502    3962
4503       0
4504    3601
Name: 분양가격, Length: 4505, dtype: int32

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4505 entries, 0 to 4504
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   지역명     4505 non-null   object
 1   규모구분    4505 non-null   object
 2   연도      4505 non-null   int64 
 3   월       4505 non-null   int64 
 4   분양가격    4505 non-null   object
dtypes: int64(2), object(3)
memory usage: 176.1+ KB


In [40]:
df['분양가격'] = df['분양가격'].astype(int)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4505 entries, 0 to 4504
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   지역명     4505 non-null   object
 1   규모구분    4505 non-null   object
 2   연도      4505 non-null   int64 
 3   월       4505 non-null   int64 
 4   분양가격    4505 non-null   int32 
dtypes: int32(1), int64(2), object(2)
memory usage: 158.5+ KB


In [42]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', ' 컴퓨터', '선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()

encoder.fit(items)
labels = encoder.transform(items)
print("인코딩 변환 값 :", labels)

인코딩 변환 값 : [1 2 5 0 4 4 3 3]


In [43]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: [' 컴퓨터' 'TV' '냉장고' '믹서' '선풍기' '전자레인지']


In [44]:
print('디코딩 원본 값:', encoder.inverse_transform([1,2,5,0,4,4,3,3]))

디코딩 원본 값: ['TV' '냉장고' '전자레인지' ' 컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [46]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [47]:
labels = labels.reshape(-1,1)
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [48]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print(oh_labels.shape)
oh_labels.toarray()

(8, 6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [50]:
import pandas as pd

df = pd.DataFrame({'items':['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기','선풍기','믹서','믹서']})
df

items
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [51]:
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터
0      True      False     False      False       False      False
1     False       True     False      False       False      False
2     False      False     False      False        True      False
3     False      False     False      False       False       True
4     False      False     False       True       False      False
5     False      False     False       True       False      False
6     False      False      True      False       False      False
7     False      False      True      False       False      False

In [52]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

In [53]:
print('feature 들의 평균 값')
print(iris_df.mean())
print("\nfeature 들의 분산값")
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [1]:
# df[['A','B']] df에서 a, b 컬럼만 가져오기