# 난수

#### #01. 작업준비

패키지 참조

In [1]:
import tensorflow as tf

### #02. 균등 분포 난수

일반적으로 각 이벤트의 결과값을 알 수 없는 경우 미래에 발생할 이벤트의 결과값 $x$가 각 예상되는 범위별로 균등한 확률로 일어날 것이라고 예상될 때 사용

#### 1) 균등 분포 난수의 사용 예

주사위에 대한 확률 

- 200번을 던지고 201번째  주사위를 던진다고 했을 때 201번째 결과값은 앞의 1에서 200번까지 결과값에 영향을 받지 않는다.
- 201번째 결과값이 1,2,3,4,5,6 각각의 결과값으로 나올 확률은 6분의 1이며 이는 앞의 1~200번째 결과값에 영향을 받아 줄어들거나 늘어나지 않는다는 것이다.
- 이처럼 미래 결과값이 경험적으로 알 수 없을 상황에서 사용하는 것이 균등분포이다.

#### 2) 균등 분포 난수 실험

##### 스칼라 형태의 균등 분포 난수

In [2]:
uni_rnd1 = tf.random.uniform(shape=[], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd1)

80


백터 형태의 균등 분포 난수

In [3]:
uni_rnd2 = tf.random.uniform(shape=[5], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd2)

[66 74 85 5 47]


행렬형태의 균등 분포 난수

In [4]:
uni_rnd3 = tf.random.uniform(shape=[2,3], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd3)

[[95 45 72]
 [43 92 20]]


텐서 형태의 균등 분포 난수

In [5]:
uni_rnd4 = tf.random.uniform(shape=[2,3,4], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd4)

[[[32 65 12 36]
  [59 84 79 15]
  [78 15 53 53]]

 [[40 62 42 89]
  [44 61 38 28]
  [96 72 72 97]]]


#### 3) 랜덤값을 갖는 행렬 곱 예시

랜덤값을 갖는 3행 2열의 행렬을 변수 x로 정의

In [6]:
x = tf.Variable(tf.random.uniform([3,2]))
tf.print(x)

[[0.729450583 0.0574190617]
 [0.758159518 0.694330454]
 [0.298957705 0.898815632]]


랜덤값을 갖는 2행 1열의 행렬 변수 y로 정의

In [7]:
y = tf.Variable(tf.random.uniform([2, 1]))
tf.print(y)

[[0.511049271]
 [0.304654837]]


### #03. 정규 분포 난수 

정규분포란 과거의 축적된 경험적 데이터를 이미 보유하고 있는 상태에서 이용하여 미래에 발생할 결과값 $x$의 각 예상되는 범위별로 발생될 확률을 어느 정도 추정할 수 있을 때 사용

#### 1) 정규 분포 난수의 사용 예

매장의 매출액 예측

- 이전 3개월의 매출이 2천만원, 2천백만원, 2천2백원 발생한 경우 평균이나 범위에 대한 예측이 가능하다.
- **`평균`에 대한 예측** → 이번달 매출은 과거 3개월의 매출평균인 2천백만원으로 예측.
- **`범위`에 대한 예측** → 최소 2천만원 ~  최대 2천2백만원까지 매출이 발생할 수 있다는 예상이 가능함.

로또 추첨

- 64개의 공 중에서 하나를 랜덤으로 추출하면, 두 번째 랜덤 범위는 첫 번째 추출된 공을 제외한 범위 안에서 생성된다.
- 만약 로또 추첨시 하나의 공을 뽑아 번호를 확인하고 그 공을 다시 추첨 대상에 포함시켰다면 균등분포 난수가 된다.

#### 2) 정규 분포 난수 실험

정규 분포 난수를 생성할 때는 평균(mean)과 표준편차(stddev)를 지정해야 한다.

##### 스칼라 형태의 정규 분포난수

In [8]:
normal_rnd1 = tf.random.normal(shape=[], mean=0.0, stddev=1.0)
tf.print(normal_rnd1)

0.684719265


백터 형태의 정규 분포 난수

In [9]:
uni_rnd2 = tf.random.normal(shape=[5], mean=0.0, stddev=1.0)
tf.print(uni_rnd2)

[0.677537501 -0.0751662776 -1.47057927 0.176774278 1.01420069]


행렬 형태의 정규 분포 난수

In [10]:
normal_rnd3 = tf.random.normal(shape=[2,3], mean=0.0, stddev=1.0)
tf.print(normal_rnd3)

[[0.871054947 -1.55431342 0.92658931]
 [-0.987052202 -1.94880855 -0.0126846144]]


텐서 형태의 정규 분포 난수

In [11]:
normal_rnd4 = tf.random.normal(shape=[2,3,4], mean=0.0, stddev=1.0)
tf.print(normal_rnd4)

[[[0.472757936 2.24387288 1.02949047 0.437186807]
  [-1.12008655 0.919504881 0.557542443 0.578286946]
  [1.50870037 0.0794188 0.0268034749 -0.2714338]]

 [[0.423689306 -0.403229743 1.16569388 0.551822662]
  [-0.56538713 3.44316101 0.761048734 1.08133042]
  [1.11074257 -2.3293004 -0.63956815 -0.00157425]]]
